### ISSUE TITLE
No alpha transparency rendering?

### ISSUE THREAD

**Issue by Koalamana9** [TheRealMJP/DeferredTexturing#19]
Why is every transparent object don't render transparency? All the leaves and decals have just black bg. It is important to include this in the demo to demonstrate performance difference between forward and bindless deferred shading. They will most likely have the same performance hit, but overall this is an essential element in any rendering, so it would be fair to take it into account.
Is there any simple and quick way to implement this?

**Comment by TheRealMJP** [comment]
I just [pushed](https://github.com/TheRealMJP/DeferredTexturing/commit/20788a8f0f8a1406c01bbdb7ce18ef36bb5bf3b9) alpha testing support for the foliage materials in both deferred and forward paths. For the forward path the alpha testing will be done in the depth prepass if it's enabled, otherwise it will be done in the main forward pass.

**Comment by Koalamana9** [comment]
Nice! But it seems there is a problem with the rendering of the material on the vase and eaves, tested in Marmoset and it shouldn't be black. The chain doesn't use transparency for some reason too
![001](https://github.com/user-attachments/assets/706408e2-2ae2-489c-b88e-621cf590a1a4)

**Comment by TheRealMJP** [comment]
Those materials are just mostly black because they're set to be full metallic, and there's no sources of indirect specular in that sample. So you only see the specular reflections from the spot/directional light sources.

I had looked at the chain texture and the alpha channel is all 1.0, so I'm not sure where the opacity information is. If you figure it out or manage to fix to texture, feel free to submit a PR and I'll merge it.

**Comment by Koalamana9** [comment]
That's true for the vase, it's really all metal. But there's definitely something wrong with the eaves and curtains at the bottom, this is in Marmoset 3 with no environment reflections, just a spotlight, and it has an albedo color there.
![001](https://github.com/user-attachments/assets/a76b5418-e11b-43d1-a310-71e0934955ba)

**Comment by Koalamana9** [comment]
I tried to fix it but it crashes with an error on startup: _DirectX Error: The parameter is incorrect_. 
If I understood this correctly, it could be caused by the original Sponza.fbx being exported with an old _FBX SDK/FBX Plugins version 2014.0.1_, and when I re-export it from Blender, it uses the new Blender specific version _stable FBX IO - 4.1.1 - 5.11.7_, and since you are using old Assimp-3.1.1 it causes an error.
