### ISSUE TITLE
Hitting assert a break in ResourceUploadEnd

### ISSUE THREAD

**Issue by chaoticbob** [TheRealMJP/DeferredTexturing#6]
Hey Matt,

Using VS2017 and hitting an break in ```ResourceUploadEnd`` in ```DX12_Upload.cpp```:
```
D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: Simultaneous-access or Buffer Resource (0x0000024F386C7940:'Decal Buffer') is still referenced by transition_barrier GPU operations in-flight on another Command Queue (0x0000024F24C657F0:'Unnamed ID3D12CommandQueue Object'). It is not safe to start write GPU operations now on this Command Queue (0x0000024F24CBB4C0:'Unnamed ID3D12CommandQueue Object'). This can result in race conditions and application instability. [ EXECUTION ERROR #1047: OBJECT_ACCESSED_WHILE_STILL_IN_USE]
D3D12: **BREAK** enabled for the previous message, which was: [ ERROR EXECUTION #1047: OBJECT_ACCESSED_WHILE_STILL_IN_USE ]
```

I poked around a bit but couldn't figure out what was going on. Was wondering if you had seen something like this on VS2017?

**Comment by TheRealMJP** [comment]
Hey there! This is a message from the validation layer. The project is configured to break into the debugger whenever the validation layer emits a warning or error.

I believe this is a bug that I never noticed because earlier versions of the validation layer didn't catch it. I'll have to look into it and see if I can fix it. In the meantime, if you'd like you can try switching over to the experimental branch. That branch currently runs clean with no validation errors, and has a lot of fixes and improvements. In particular I re-wrote the "UpdateData" path for using  the copy queue to update the contents of buffer resources from a DEFAULT heap to make it more useful, and also to fix some synchronization issues. It also has support for the new "dxc" shader compiler that's based on LLVM.

**Comment by TheRealMJP** [comment]
I ended up just merging the experimental branch back into master, so it should run clean now without any warnings or errors.

**Comment by chaoticbob** [comment]
Sorry for the delayed thank you! Appreciate it!
